/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zyx.filter.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 判定结果
 */
public enum TJudgeResult implements org.apache.thrift.TEnum {
  OK(0),
  /**
   * 正常发表
   */
  ADJUST(1),
  /**
   * 部分关键字被调整后发表
   */
  NOTICE(2),
  /**
   * 发表并提醒管理员检查(发表内容也会被调整)
   */
  CHECK(3),
  /**
   * 待审核(发表内容也会被调整)
   */
  FORBIDDEN(4);

  private final int value;

  private TJudgeResult(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TJudgeResult findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return ADJUST;
      case 2:
        return NOTICE;
      case 3:
        return CHECK;
      case 4:
        return FORBIDDEN;
      default:
        return null;
    }
  }
}
