/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zyx.filter.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 文本过滤器
 */
public class TTextFilter implements org.apache.thrift.TBase<TTextFilter, TTextFilter._Fields>, java.io.Serializable, Cloneable, Comparable<TTextFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTextFilter");

  private static final org.apache.thrift.protocol.TField FILTER_KEYWORDS_FIELD_DESC = new org.apache.thrift.protocol.TField("filter_keywords", org.apache.thrift.protocol.TType.LIST, (short)11);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TTextFilterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TTextFilterTupleSchemeFactory());
  }

  public List<TFilterKeyword> filter_keywords; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILTER_KEYWORDS((short)11, "filter_keywords");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 11: // FILTER_KEYWORDS
          return FILTER_KEYWORDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.FILTER_KEYWORDS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILTER_KEYWORDS, new org.apache.thrift.meta_data.FieldMetaData("filter_keywords", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TFilterKeyword.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTextFilter.class, metaDataMap);
  }

  public TTextFilter() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TTextFilter(TTextFilter other) {
    if (other.isSetFilter_keywords()) {
      List<TFilterKeyword> __this__filter_keywords = new ArrayList<TFilterKeyword>(other.filter_keywords.size());
      for (TFilterKeyword other_element : other.filter_keywords) {
        __this__filter_keywords.add(new TFilterKeyword(other_element));
      }
      this.filter_keywords = __this__filter_keywords;
    }
  }

  public TTextFilter deepCopy() {
    return new TTextFilter(this);
  }

  @Override
  public void clear() {
    this.filter_keywords = null;
  }

  public int getFilter_keywordsSize() {
    return (this.filter_keywords == null) ? 0 : this.filter_keywords.size();
  }

  public java.util.Iterator<TFilterKeyword> getFilter_keywordsIterator() {
    return (this.filter_keywords == null) ? null : this.filter_keywords.iterator();
  }

  public void addToFilter_keywords(TFilterKeyword elem) {
    if (this.filter_keywords == null) {
      this.filter_keywords = new ArrayList<TFilterKeyword>();
    }
    this.filter_keywords.add(elem);
  }

  public List<TFilterKeyword> getFilter_keywords() {
    return this.filter_keywords;
  }

  public TTextFilter setFilter_keywords(List<TFilterKeyword> filter_keywords) {
    this.filter_keywords = filter_keywords;
    return this;
  }

  public void unsetFilter_keywords() {
    this.filter_keywords = null;
  }

  /** Returns true if field filter_keywords is set (has been assigned a value) and false otherwise */
  public boolean isSetFilter_keywords() {
    return this.filter_keywords != null;
  }

  public void setFilter_keywordsIsSet(boolean value) {
    if (!value) {
      this.filter_keywords = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILTER_KEYWORDS:
      if (value == null) {
        unsetFilter_keywords();
      } else {
        setFilter_keywords((List<TFilterKeyword>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILTER_KEYWORDS:
      return getFilter_keywords();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILTER_KEYWORDS:
      return isSetFilter_keywords();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TTextFilter)
      return this.equals((TTextFilter)that);
    return false;
  }

  public boolean equals(TTextFilter that) {
    if (that == null)
      return false;

    boolean this_present_filter_keywords = true && this.isSetFilter_keywords();
    boolean that_present_filter_keywords = true && that.isSetFilter_keywords();
    if (this_present_filter_keywords || that_present_filter_keywords) {
      if (!(this_present_filter_keywords && that_present_filter_keywords))
        return false;
      if (!this.filter_keywords.equals(that.filter_keywords))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TTextFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFilter_keywords()).compareTo(other.isSetFilter_keywords());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilter_keywords()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filter_keywords, other.filter_keywords);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TTextFilter(");
    boolean first = true;

    if (isSetFilter_keywords()) {
      sb.append("filter_keywords:");
      if (this.filter_keywords == null) {
        sb.append("null");
      } else {
        sb.append(this.filter_keywords);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TTextFilterStandardSchemeFactory implements SchemeFactory {
    public TTextFilterStandardScheme getScheme() {
      return new TTextFilterStandardScheme();
    }
  }

  private static class TTextFilterStandardScheme extends StandardScheme<TTextFilter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TTextFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 11: // FILTER_KEYWORDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.filter_keywords = new ArrayList<TFilterKeyword>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  TFilterKeyword _elem2;
                  _elem2 = new TFilterKeyword();
                  _elem2.read(iprot);
                  struct.filter_keywords.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setFilter_keywordsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TTextFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.filter_keywords != null) {
        if (struct.isSetFilter_keywords()) {
          oprot.writeFieldBegin(FILTER_KEYWORDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.filter_keywords.size()));
            for (TFilterKeyword _iter3 : struct.filter_keywords)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TTextFilterTupleSchemeFactory implements SchemeFactory {
    public TTextFilterTupleScheme getScheme() {
      return new TTextFilterTupleScheme();
    }
  }

  private static class TTextFilterTupleScheme extends TupleScheme<TTextFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TTextFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFilter_keywords()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFilter_keywords()) {
        {
          oprot.writeI32(struct.filter_keywords.size());
          for (TFilterKeyword _iter4 : struct.filter_keywords)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TTextFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.filter_keywords = new ArrayList<TFilterKeyword>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            TFilterKeyword _elem7;
            _elem7 = new TFilterKeyword();
            _elem7.read(iprot);
            struct.filter_keywords.add(_elem7);
          }
        }
        struct.setFilter_keywordsIsSet(true);
      }
    }
  }

}

