/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zyx.filter.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 时间单位
 */
public enum TTimeUnit implements org.apache.thrift.TEnum {
  MILLISECONDS(1),
  SECONDS(2),
  MINUTES(3),
  HOURS(4),
  DAYS(5),
  WEEKS(6),
  MONTHS(7),
  YEARS(8);

  private final int value;

  private TTimeUnit(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TTimeUnit findByValue(int value) { 
    switch (value) {
      case 1:
        return MILLISECONDS;
      case 2:
        return SECONDS;
      case 3:
        return MINUTES;
      case 4:
        return HOURS;
      case 5:
        return DAYS;
      case 6:
        return WEEKS;
      case 7:
        return MONTHS;
      case 8:
        return YEARS;
      default:
        return null;
    }
  }
}
